---
# Source: wordpress/templates/storage.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gce-provision
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
reclaimPolicy: Retain
---
# Source: wordpress/templates/storage.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-pvc
  namespace: wp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "gce-provision"
---
# Source: wordpress/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - name: http
      port: 80 
      targetPort: 9000
---
# Source: wordpress/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      helm.sh/chart: wordpress
      app.kubernetes.io/managed-by: Helm
  template:
    metadata:
      labels:
        helm.sh/chart: wordpress
        app.kubernetes.io/managed-by: Helm
    spec:
      imagePullSecrets:
      - name: registry-sa
      containers:
        - name: wordpress
          image: europe-west1-docker.pkg.dev/wp-project-manage/wp-project-infra-registry/wp-image:dev
          imagePullPolicy: Always
          ports:
          - containerPort: 9000
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: db_host
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: db_name
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: db_password
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: db_username
          volumeMounts: 
            - mountPath: /var/www/html/wp-content
              name: wordpress-content
      volumes: 
      - name: wordpress-content
        persistentVolumeClaim:
          claimName: wordpress-pvc
